server: 
  port: 8086
spring: 
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: "jdbc:mysql://localhost:3306/barclaysdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true" #"jdbc:mysql://mysql-standalone:3306/ehousing_cdac?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"   
    username: root
    initialization-mode: always
  jackson: 
    serialization: 
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  jpa: 
    generate-ddl: true
    hibernate.ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true